# Generated by Django 4.2.1 on 2024-03-02 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_reversed',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_reserved',
            field=models.BooleanField(default=False, verbose_name='Запас'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='permission',
            field=models.BooleanField(choices=[(True, 'Доступно'), (False, 'Не доступно')], default=0, verbose_name='Разрешение на доступ'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.product', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='Полностью заполнена'),
        ),
        migrations.AlterField(
            model_name='group',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.product', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='group',
            name='reserved_group',
            field=models.BooleanField(verbose_name='Неполная группа(запас)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.JSONField(verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.product', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(max_length=255, unique=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_group_students_qty',
            field=models.PositiveSmallIntegerField(verbose_name='Максимальное количество студентов в группе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_group_students_qty',
            field=models.PositiveSmallIntegerField(verbose_name='Минимальное количество студентов в группе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='product',
            name='students',
            field=models.ManyToManyField(related_name='products', through='edu.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
