# Generated by Django 4.2.1 on 2024-03-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_remove_enrollment_is_reversed_enrollment_is_reserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата поступления'),
        ),
        migrations.AddField(
            model_name='product',
            name='rule',
            field=models.BooleanField(choices=[(True, 'По умолчанию'), (False, 'Умное')], default=1, verbose_name='Правило распределения по группам'),
        ),
    ]
