# Generated by Django 4.2.1 on 2024-03-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_remove_group_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='Полностью заполнена'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления'),
        ),
    ]
